language: erlang
# http://stackoverflow.com/a/24600210/1793234
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
# Apply the replacement to rebar.config as well.
before_install:
  - sed -i 's/git@github.com[:\/]/https:\/\/github.com\//' .gitmodules rebar.config
  - git submodule update --init --recursive
install: true
before_script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod 755 rebar3
script:
  - ./rebar3 eunit
notifications:
  recipients:
    - quasiquoting@gmail.com
otp_release:
  - 18.1
  - 18.0
